### ISSUE TITLE
installation error: rdata.rdb file not found

### ISSUE THREAD

**Issue by liezeltamon** [robertamezquita/marge#4]
(R-3.6.1)
I am getting the same error both when installing the latest version from github and the latest stable version from bitbucket.

<img width="1591" alt="Screenshot 2019-09-11 at 14 49 15" src="https://user-images.githubusercontent.com/45236685/65157400-97182600-da28-11e9-98fa-5509fa8d333b.png">

**Comment by robertamezquita** [comment]
Yep I'm getting the same exact error on my machine. But I can't seem to find a call to `Rdata.rdb` in the code..hmm. Will look into this further.

**Comment by robertamezquita** [comment]
The offending bug ended up being this in the `utils.R` file:

```
## Load HOMER_motifs data
HOMER_motifs <- NULL
data("HOMER_motifs", package = "marge", envir = environment())
```

Something funky was going on with how it loaded the data, and this line was a bit of a legacy, so I removed it, and moved the data loading required by `.append_motif_pwm` into that function directly.

Let me know if this resolves the issue on your end!

**Comment by liezeltamon** [comment]
installed! thanks a lot
